names=['changjiangrever','qilimazhaluomountain','trafic','bicycle','hiking']
print(names,len(names),names[0],names[3])
names.append('cake')
names.insert(0,'cook')
print(names)
del names[0]
print(names)
names.pop()
names.pop(0)
print(names)
names.remove('qilimazhaluomountain')
print(names)
print("\n")
names.sort()
print(names)
names.sort(reverse=True)
print(names)
print(sorted(names))
print(names)
names.reverse()
print(names)
names.reverse()
print(names)

